import Head from "next/head";
import { Inter } from "next/font/google";
import NavBar from "./../Components/Nav/index";
import MainSlider from "@/Components/Sliders/MainSlider";
import BrandsSlider from "@/Components/Sliders/BrandsSlider";
import Footer from "@/Components/Footer";
import Deals from "./../Components/Deals/index";
import ProductSlider from "./../Components/Sliders/ProductSlider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col overflow-hidden">
        <NavBar />
        <div className="h-[20vh] lg:h-[75vh] overflow-hidden">
          <MainSlider
            slides={[
              "https:gazef.s3.amazonaws.com/FebApiTask/media/api/images/sliders/Mask_Group_4.png",
              "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/sliders/bhc8023-1-1.jpg",
            ]}
          />
        </div>
        <BrandsSlider
          slides={[
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Screenshot_2022-11-21_at_8.11.51_PM.png",
              name: "Footwear",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Group_1333.png",
              name: "Outlet store",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/0136047_adidas-zne-sportswear-hoodie_h08191_standard-view.png",
              name: "Sports",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Screenshot_2022-11-21_at_8.13.50_PM.png",
              name: "Best Sellers",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Screenshot_2022-11-21_at_8.14.33_PM.png",
              name: "Bags",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Screenshot_2022-11-21_at_8.11.51_PM.png",
              name: "Footwear",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/categories/Group_1333.png",
              name: "Outlet store",
            },
          ]}
        />
        <div className="h-[80vh] lg:h-[40vh] overflow-hidden">
          <MainSlider
            hasBanner={true}
            banner={1}
            slides={["https://bit.ly/41Yc0GF"]}
          />
        </div>
        <BrandsSlider
          backGround="#2D2F7D"
          slides={[
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_5903342.png",
              sale_percentage: "23",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_1126700.png",
              sale_percentage: "22",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_1729325.png",
              sale_percentage: "11",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_5903342.png",
              sale_percentage: "55",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_1126700.png",
              sale_percentage: "77",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_1729325.png",
              sale_percentage: "88",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_5903342.png",
              sale_percentage: "67",
            },
            {
              image:
                "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/brands/kindpng_1126700.png",
              sale_percentage: "47",
            },
          ]}
        />
        <div className="h-[50vh] overflow-hidden">
          <MainSlider
            hasBanner={true}
            banner={2}
            slides={[
              "https://bit.ly/3ZDmGJ5",
              "./sale-banner.png",
              "https://bit.ly/3T6U3Bu",
            ]}
          />
        </div>
        <div className="w-full h-[35vh]">
          <ProductSlider
            title="featured items"
            slides={[
              {
                name: "test3",
                image:
                  "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/items/Screenshot_2022-11-21_at_8.34.38_PM.png",
                type: "featured",
                price_before_sale: 444,
                price_after_sale: 222,
              },
            ]}
          />
        </div>
        <div className="w-full h-[35vh]">
          <ProductSlider
            title="Most Viewed items"
            slides={[
              {
                name: "test3",
                image:
                  "https://gazef.s3.amazonaws.com/FebApiTask/media/api/images/items/Screenshot_2022-11-21_at_8.34.38_PM.png",
                type: "featured",
                price_before_sale: 444,
                price_after_sale: 222,
              },
            ]}
          />
        </div>
        <Deals />
        <Footer />
      </main>
    </>
  );
}
